language : android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository
script: ./gradlew build

notifications:
  slack: codehere:jVcvzPcR8l219FndGLo6Lz8y